---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB8QPj8mq0Xt6HoSSsp207S2vJdpHp9XmP9g9JzCjltzniiEQS0bm41XzhdkEYWMJtohcC6gWAQHJmGphO6qAnhFDuS8nfTDrXFiGc6epfK76R/1nGbVj+SZOJ5NfqAxJoj+ABOzQpRx7T9ajs0zIb/Am93ujbOz55GlBH1+hjvbEgXpwFi92q0Ty/MWKZupq7AjPT2H3kINFZQ7zl7l3zV/xx04eYEo4sN9OVf7rQKI2S2ngsB4BYZoZuA+3GemJWR9I71trUorPMjppwztHM23h7g7UIwvKIlTlEQ8v+ZyRn6iqyAbITE1eIO9gZ2QKqgzv6MM1eQ/m/HMA9MUyBnpzyvOrkDhEa8Sc3ozKEKLoaz1e2g/Y35WfcXN7Txoim3RwIaHMwXcXs3mfNWcfC3YRnzMPbFb3eT3PZdN9CW2h+InmSjnl/SfE8x6VljA2ukXH2HP3jN1UYkHxj3zo/lxoGb4hi9qHZ3uWXEhBdruw53TIYZ9xTjGSLkCbDiSZlHFYzdT8LcjcDpY5D57JB/d6H8AtJNoCJXeTCQWq5yqiqIlhQsUhxqipzh1IT2Y0vjEHYwyT1uKYdss3Jgvp8chksCZ9MbPq6R3UaoH+rE1vfP3WqvyEZ1VKkPbhyayueubXXC0ZjvKDpxb5p1oSxU+Y+RYqoOnQ4V3Ks1GHGzwkEYNfJFqzc0OrHNesiHpgrJOUF3tcY7+lw3LcwH7LwdyrW8DL/7TmxBftp8JriQ
    admin-user: AgAZUGsDVmcQRfhr/UTt7XjOuJ3+DP/t9ravOAxc/3px0A/foiDx95peAQABVS/XnyoGJRBC+4RY4F07f8vXvfM50lrSy/UieF5g10SbN6be2WfTA9a0mNtiWqWtJqYdc/Dr8j5uVzo49q+6y6/kPmKWQBMgdW1oklCxQlJ6RZmVdVacv6UXr7dwl/aghsGrTIQCMJyhxKWAFgJVG4NdIb4IrFSe/X3ZE4n4yZdoCY2ite1ndZdsr10ey1TtJ39bDT/sHQeaTGLWdOUBxpGo3RSEGH9MRzG8ASYLjkej/ocWskSk+JtnpU4IKwiU/az/KpCjmyS/RnvN0aE4QxexktDkiL56mZmb44/ME51yCqZGMddPxJvPbSdptgXw8wX2MZOZOtedvMj6OEnWzD1XGYTWDmliV6eeHF42Mdh1HkURvuNEeBWulCVnVGUklfeoTOwMUvSHRTd9zbYssuzV4LrQGxY4ajFIDsxvV0Alp1WbFShaR2M4DqNXRgymz+iPFAWUkT+bQ6Kinedt2+dtQdk7Ok1h6kuKnprJbgi2cygBvuW0wGFNI8tqUmW05mcHzr/Je0InqOWeq4gpdPzhseWgVA3UtsnbE1tFwNgfQi6zaKR6o1o8raDI5CbxTvNzXDFOgxXxHPxcqY3dG/e/6V+Q2ULczp7gJiD1O+gWEOuVgtSm8RFYCvRb/Dom7j1g6sxgq0p9+g==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
