apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bls-workloads
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/CalmAfterReboot/BLS-platform
          revision: HEAD
          directories:
          - path: k8s/workloads/*
      - clusters: {}
  template:
    metadata:
      name: '{{path.basename}}-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/CalmAfterReboot/BLS-platform
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
